name: Continuous Integration / Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the image
        run: docker build -t chatsift/discordjs-cache-proxy:latest .

      - name: Tag the image with major if applicable
        # Seriously couldn't get this to work under a GH if
        run: |
          if [ $(cut -d '.' -f1 <<< $(jq --raw-output '.version' package.json)) -ne "0" ]; then
            docker tag chatsift/discordjs-cache-proxy chatsift/discordjs-cache-proxy:$(cut -d '.' -f1 <<< $(jq --raw-output '.version' package.json))
          fi

      - name: Push image to DockerHub
        run: docker push --all-tags chatsift/discordjs-cache-proxy
